server:
  port : 9595

spring.datasource.url: jdbc:h2:file:./camunda-h2-database

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    allow-bean-definition-overriding: true
  activemq:
    broker-url: tcp://localhost:61616
      
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks